name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ] # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Build
        working-directory: ./frontend
        run: |
          npm install
          chmod +x node_modules/.bin/vite
          npm run build

      - name: Deploy to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: 13.205.37.9
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 443
          source: "frontend/dist/*"
          target: "/app/frontend"
          strip_components: 2

      - name: Finalize Deployment on Server
        uses: appleboy/ssh-action@master
        with:
          host: 13.205.37.9
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 443
          script: |
            sudo mkdir -p /app/frontend
            sudo chown -R ubuntu:ubuntu /app
            sudo /app/deploy-frontend.sh
